ORG 1000H

MSJ DB "INGRESE UN NUMERO:"
FIN DB ?

ORG 1500H

NUMEROS DB "0123456789"
MSJ2 DB "CARACTER NO VALIDO"
NUM DB ?

ORG 3000H

ES_NUM: PUSH BX
        MOV DH,[BX]
        MOV BX, OFFSET NUMEROS
        MOV DL,10
FOR:    CMP DH, [BX]
        JZ ESN
        INC BX
        DEC DL    
        CMP DL,0
        JNZ FOR
        MOV DX, 00H
        JMP VOLVER
ESN:    MOV DX, 0FFH
VOLVER: POP BX
        RET


ORG 2000H
    MOV BX, OFFSET MSJ
    MOV AL, OFFSET FIN-OFFSET MSJ
    INT 7
    MOV BX, OFFSET NUM
    INT 6
    CALL ES_NUM
    CMP DX, 0FFH
    JZ OK
    MOV BX, OFFSET MSJ2
    MOV AL, OFFSET NUM - OFFSET MSJ2
JMP WR
OK: MOV AL, 1
WR: INT 7
    MOV CL, NUM
    HLT
END