PIO EQU 30H
HAND EQU 40H

ORG 1000H

MSJ DB "THE GRAND WAZOO"
FIN DB ?

ORG 3000H

INI_HND:PUSH AX
    IN AL, HAND+1
    AND AL, 127         ;bit 7 de Estado en 0
    OUT HAND+1, AL
    POP AX
    RET

ORG 2000H
    CALL INI_HND        ;inicializamos el HANDSHAKE
    MOV BX, OFFSET MSJ
    MOV CL, OFFSET FIN - OFFSET MSJ
PLL:IN AL, HAND+1       ;polling
    AND AL, 1
    JNZ PLL
    MOV AL,[BX]
    OUT HAND, AL
    INC BX
    DEC CL
    JNZ PLL
    INT 0
    END